language: php
php:
 - "5.3"
 - "5.4"
 - "5.5"

before_install:
 - composer self-update
 - composer install --dev
 - pear install pear/PHP_CodeSniffer
 - phpenv rehash

script:
 - phpunit -c tests --coverage-clover ./report/clover.xml
 - phpcs --standard=PSR2 ./src/ ./tests/

after_script:
 - ./vendor/bin/coveralls -v
