<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MyPages\Module'         => __DIR__ . '/src/MyPages/Module.php',
    'MyPages\PageController' => __DIR__ . '/src/MyPages/PageController.php',
);
